import Image from 'next/image'

// Zenn API does not return ogp_image_url in the articles list endpoint.
// OGP images are dynamically generated by Zenn using emoji + title.
// We replicate Zenn's card style with a large emoji on a gradient background.

type ZennArticle = {
  id: number
  title: string
  slug: string
  emoji: string
  published_at: string
  path: string
  article_type: string
}

type ZennResponse = {
  articles: ZennArticle[]
}

async function fetchZennArticles(): Promise<ZennArticle[]> {
  try {
    const res = await fetch(
      'https://zenn.dev/api/articles?username=be_the_light&order=latest',
      { next: { revalidate: 86400 } }
    )
    if (!res.ok) return []
    const data: ZennResponse = await res.json()
    return data.articles.slice(0, 6)
  } catch {
    return []
  }
}

export default async function ZennArticles() {
  const articles = await fetchZennArticles()

  if (articles.length === 0) return null

  return (
    <section className="w-full max-w-5xl">
      <h2 className="text-2xl font-bold tracking-widest mb-6">
        <div className="flex items-center gap-2">
          ✍️
          <Image src="/zenn.svg" width={28} height={28} alt="Zenn logo" />
          Zenn Articles
        </div>
      </h2>
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {articles.map((article) => (
          <a
            key={article.id}
            href={`https://zenn.dev${article.path}`}
            target="_blank"
            rel="noopener noreferrer"
            className="group block rounded-xl border border-neutral-200 dark:border-neutral-700 overflow-hidden transition-colors bg-white dark:bg-neutral-900 hover:border-gray-400 hover:bg-gray-50 hover:dark:border-neutral-500 hover:dark:bg-neutral-800/50"
          >
            <div className="aspect-[16/9] w-full bg-gradient-to-br from-blue-50 to-sky-100 dark:from-blue-950 dark:to-sky-900 flex flex-col items-center justify-center px-4 gap-2">
              <span className="text-5xl drop-shadow-sm">{article.emoji}</span>
              <p className="text-sm font-bold text-neutral-700 dark:text-neutral-200 text-center line-clamp-2 leading-snug">
                {article.title}
              </p>
            </div>
            <div className="px-4 py-3 flex items-center justify-between">
              <p className="text-xs text-neutral-500 dark:text-neutral-400">
                {new Date(article.published_at).toLocaleDateString('ja-JP')}
              </p>
              <span className="text-xs font-semibold group-hover:underline">
                Read
                <span className="inline-block transition-transform group-hover:translate-x-1 ml-0.5">
                  →
                </span>
              </span>
            </div>
          </a>
        ))}
      </div>
      <div className="mt-8 text-center">
        <a
          href="https://zenn.dev/be_the_light"
          target="_blank"
          rel="noopener noreferrer"
          className="inline-block rounded-lg border border-neutral-300 dark:border-neutral-600 px-6 py-3 text-sm font-semibold tracking-wide transition-colors hover:bg-gray-100 hover:dark:bg-neutral-800"
        >
          View more articles →
        </a>
      </div>
    </section>
  )
}
